# Generated by Django 5.2.11 on 2026-02-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_confidence', models.FloatField(blank=True, help_text='Average AssemblyAI word-level confidence (0.0 – 1.0).', null=True)),
                ('transcript_word_count', models.IntegerField(blank=True, help_text='Total word count in the raw transcript.', null=True)),
                ('soap_sections_complete', models.IntegerField(blank=True, help_text='Number of SOAP sections with substantive content (0 – 4).', null=True)),
                ('groq_prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('groq_completion_tokens', models.IntegerField(blank=True, null=True)),
                ('groq_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metric', to='encounters.encounter')),
            ],
            options={
                'verbose_name': 'Quality Metric',
                'verbose_name_plural': 'Quality Metrics',
            },
        ),
    ]
