# Generated by Django 5.2.11 on 2026-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_qualitymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='patient_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
